/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as shellRouteImport } from './routes/shell'
import { Route as homeRouteImport } from './routes/home'
import { Route as catalogMountRouteImport } from './routes/catalog-mount'

const shellRoute = shellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const homeRoute = homeRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const catalogMountRoute = catalogMountRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => shellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeRoute
  '/catalog': typeof catalogMountRoute
}
export interface FileRoutesByTo {
  '/': typeof homeRoute
  '/catalog': typeof catalogMountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof homeRoute
  '/_shell': typeof shellRouteWithChildren
  '/_shell/catalog': typeof catalogMountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalog'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog'
  id: '__root__' | '/' | '/_shell' | '/_shell/catalog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeRoute: typeof homeRoute
  shellRoute: typeof shellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof shellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/catalog': {
      id: '/_shell/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof catalogMountRouteImport
      parentRoute: typeof shellRoute
    }
  }
}

interface shellRouteChildren {
  catalogMountRoute: typeof catalogMountRoute
}

const shellRouteChildren: shellRouteChildren = {
  catalogMountRoute: catalogMountRoute,
}

const shellRouteWithChildren = shellRoute._addFileChildren(shellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  homeRoute: homeRoute,
  shellRoute: shellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
